[package]
name = "blinker-differential"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blinker-test-support = { workspace = true }
object = { workspace = true }

[dev-dependencies]
blinker-output = { workspace = true }
blinker-layout = { workspace = true }
blinker-macho = { workspace = true }
