[package]
name = "blinker-link"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blinker-cache = { workspace = true }
blinker-archive = { workspace = true }
blinker-layout = { workspace = true }
blinker-macho = { workspace = true }
blinker-output = { workspace = true }
blinker-relocations = { workspace = true }
blinker-symbols = { workspace = true }
blinker-tbd = { workspace = true }

[dev-dependencies]
blinker-cache = { workspace = true }
blinker-test-support = { workspace = true }
